import json
import os

comprehensive_plans = {
    "prayer_and_communion.json": {
        "title": "Prayer and Communion",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Matthew 6:5-8", "overview": "Jesus teaches about prayer: avoid hypocrisy, pray in secret, don't use empty phrases like pagans. Your Father knows what you need before you ask.", "reflection": "What does praying in secret mean? How do you avoid empty repetition? How does knowing God already knows your needs affect your prayers?", "prayer": "Ask God to teach you authentic prayer that connects with Him genuinely."},
            {"day": 2, "passage": "{{translation}}: Matthew 6:9-13", "overview": "Jesus teaches the Lord's Prayer: hallowing God's name, seeking His kingdom, daily bread, forgiveness, protection from temptation. This model prayer covers essential elements.", "reflection": "What does each petition mean? How do you hallow God's name? What does seeking God's kingdom first look like?", "prayer": "Pray through the Lord's Prayer slowly, reflecting on each petition."},
            {"day": 3, "passage": "{{translation}}: Luke 18:1-8", "overview": "Jesus tells a parable about a persistent widow to show disciples they should always pray and not lose heart. God will give justice to His elect who cry to Him day and night.", "reflection": "What does persistent prayer look like? When are you tempted to give up praying? How does God's justice encourage persistent prayer?", "prayer": "Commit to persisting in prayer without losing heart, trusting God will answer."},
            {"day": 4, "passage": "{{translation}}: Philippians 4:6-7", "overview": "Paul instructs believers not to be anxious but bring everything to God in prayer and supplication with thanksgiving. God's peace will guard their hearts and minds.", "reflection": "What anxieties should you bring to God? How does thanksgiving change prayer? How have you experienced God's peace?", "prayer": "Bring your anxieties to God with thanksgiving and receive His peace."},
            {"day": 5, "passage": "{{translation}}: 1 Thessalonians 5:16-18", "overview": "Paul commands constant rejoicing, unceasing prayer, and thanksgiving in all circumstances. This is God's will for believers in Christ Jesus.", "reflection": "How do you pray without ceasing? What does thanksgiving in all circumstances mean? How is this God's will?", "prayer": "Ask God to help you maintain constant prayer and thanksgiving."},
            {"day": 6, "passage": "{{translation}}: James 5:13-16", "overview": "James instructs believers to pray in trouble, sing in cheerfulness, call elders to pray for the sick, confess sins to one another. The prayer of a righteous person is powerful and effective.", "reflection": "How do you pray in different circumstances? When do you confess sins to others? What makes prayer powerful?", "prayer": "Commit to fervent, righteous prayer and confession when needed."},
            {"day": 7, "passage": "{{translation}}: John 15:7", "overview": "Jesus promises that if believers abide in Him and His words abide in them, they can ask whatever they wish and it will be done. Answered prayer flows from abiding relationship.", "reflection": "What does abiding in Christ mean? How do His words abide in you? How does abiding affect what you pray?", "prayer": "Ask Jesus to teach you to abide in Him so your prayers align with His will."}
        ]
    },

    "sermon_on_the_mount.json": {
        "title": "Sermon on the Mount",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Matthew 5:3-12", "overview": "Jesus begins with the Beatitudes, pronouncing blessing on the poor in spirit, those who mourn, the meek, those hungering for righteousness, the merciful, pure in heart, peacemakers, and persecuted.", "reflection": "Which beatitude speaks most to you? What does Jesus' definition of blessing challenge? How do you pursue these characteristics?", "prayer": "Ask God to form in you the character Jesus blesses."},
            {"day": 2, "passage": "{{translation}}: Matthew 5:13-16", "overview": "Jesus calls His disciples salt of the earth and light of the world, commanding them to let their light shine so others see good works and glorify God.", "reflection": "How are you salt and light? What good works make your light visible? Where might you be hiding your light?", "prayer": "Ask God to help you be salt and light, shining for His glory."},
            {"day": 3, "passage": "{{translation}}: Matthew 5:21-26", "overview": "Jesus teaches that anger is like murder—reconciliation is urgent. Don't come to worship with unreconciled relationships. Settle matters quickly.", "reflection": "Who do you need to reconcile with? How does anger relate to murder? What prevents you from seeking reconciliation?", "prayer": "Ask God to reveal any unreconciled relationships and give you courage to seek peace."},
            {"day": 4, "passage": "{{translation}}: Matthew 5:43-48", "overview": "Jesus commands loving enemies and praying for persecutors, to be sons of the Father who makes sun rise on evil and good. Be perfect as your heavenly Father is perfect.", "reflection": "Who is your enemy? How do you pray for those who persecute you? What does perfection in love mean?", "prayer": "Pray for specific enemies and persecutors, asking God for love toward them."},
            {"day": 5, "passage": "{{translation}}: Matthew 6:19-24", "overview": "Jesus warns against storing treasures on earth versus heaven. Where your treasure is, your heart will be. You cannot serve both God and money.", "reflection": "Where is your treasure? What does your spending reveal about your heart? How do you serve God rather than money?", "prayer": "Ask God to help you store treasure in heaven and serve only Him."},
            {"day": 6, "passage": "{{translation}}: Matthew 6:25-34", "overview": "Jesus commands not to be anxious about life, food, clothing. God feeds birds and clothes flowers—He will care for you. Seek first His kingdom and righteousness.", "reflection": "What do you worry about? How does God's care for creation encourage you? What does seeking His kingdom first mean?", "prayer": "Cast your anxieties on God and commit to seeking His kingdom first."},
            {"day": 7, "passage": "{{translation}}: Matthew 7:1-5", "overview": "Jesus warns against judging others while having your own faults. Remove the log from your own eye before addressing the speck in another's eye.", "reflection": "Who are you judging? What log is in your own eye? How can you address your own sin first?", "prayer": "Confess your judgmental attitudes and ask God to help you see your own faults."},
            {"day": 8, "passage": "{{translation}}: Matthew 7:7-11", "overview": "Jesus encourages asking, seeking, knocking—God gives good gifts to His children. If earthly fathers give good gifts, how much more will the heavenly Father.", "reflection": "What do you need to ask for? How does God's character as Father encourage your asking? What good gifts has He given?", "prayer": "Ask, seek, and knock, trusting your heavenly Father to give good gifts."},
            {"day": 9, "passage": "{{translation}}: Matthew 7:24-27", "overview": "Jesus concludes: whoever hears and does His words is like a wise man building on rock; whoever hears without doing is like a fool building on sand.", "reflection": "Are you a hearer only or also a doer? What foundation is your life built on? What storms have tested your foundation?", "prayer": "Commit to being a doer of Jesus' words, building on the solid rock."}
        ]
    },

    "spiritual_warfare.json": {
        "title": "Spiritual Warfare",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Ephesians 6:10-13", "overview": "Paul reveals the true nature of Christian struggle: not against flesh and blood but against spiritual forces of evil. Believers must be strong in the Lord and put on God's armor.", "reflection": "What spiritual battles are you facing? How do you strengthen yourself in the Lord? Why is recognizing the spiritual dimension important?", "prayer": "Ask God to open your eyes to spiritual realities and strengthen you in Him."},
            {"day": 2, "passage": "{{translation}}: Ephesians 6:14-17", "overview": "Paul describes each piece of armor: belt of truth, breastplate of righteousness, shoes of gospel readiness, shield of faith, helmet of salvation, sword of the Spirit (God's word).", "reflection": "Which piece of armor do you need most? How do you put on each piece? What role does God's Word play?", "prayer": "Ask God to help you daily put on the full armor and wield His Word effectively."},
            {"day": 3, "passage": "{{translation}}: 2 Corinthians 10:3-5", "overview": "Paul explains that spiritual weapons have divine power to destroy strongholds, arguments, and pretensions against knowing God, taking every thought captive to obey Christ.", "reflection": "What strongholds exist in your thinking? What arguments oppose knowing God? How do you take thoughts captive?", "prayer": "Ask God to demolish strongholds and help you bring every thought into obedience to Christ."},
            {"day": 4, "passage": "{{translation}}: James 4:7", "overview": "James provides a battle strategy: submit to God, resist the devil, and he will flee. Victory comes through surrender to God and active resistance of evil.", "reflection": "What does submitting to God look like? How do you actively resist the devil? What areas need greater submission?", "prayer": "Submit yourself fully to God and ask for strength to resist the devil."},
            {"day": 5, "passage": "{{translation}}: 1 Peter 5:8-9", "overview": "Peter warns that the devil prowls like a roaring lion seeking someone to devour. Believers must be sober-minded, watchful, and resist him firm in faith.", "reflection": "Where is the enemy prowling in your life? How do you remain watchful? What does resisting firm in faith mean?", "prayer": "Ask God for alertness to the enemy's schemes and firm faith to resist."},
            {"day": 6, "passage": "{{translation}}: Revelation 12:10-11", "overview": "A heavenly voice declares believers conquer the accuser by the blood of the Lamb, the word of their testimony, and not loving their lives unto death.", "reflection": "How do you overcome accusation? What is your testimony? What does not loving your life mean?", "prayer": "Thank Jesus for His blood that conquers the accuser and strengthen your testimony."},
            {"day": 7, "passage": "{{translation}}: Colossians 2:13-15", "overview": "Paul declares that God made believers alive with Christ, forgiving all trespasses, canceling the record of debt, disarming rulers and authorities, triumphing over them in the cross.", "reflection": "What has Christ's victory accomplished? How does the cross disarm spiritual powers? What freedom does this bring?", "prayer": "Thank Jesus for His complete victory over spiritual powers through the cross."}
        ]
    },

    "the_holy_spirit's_work.json": {
        "title": "The Holy Spirit's Work",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: John 14:16-17", "overview": "Jesus promises to send another Helper who will be with believers forever—the Spirit of truth whom the world cannot receive. He dwells with and will be in believers.", "reflection": "Who is the Holy Spirit? What does it mean that He is your Helper? How is the Spirit with you?", "prayer": "Thank Jesus for sending the Holy Spirit and welcome His presence and help."},
            {"day": 2, "passage": "{{translation}}: John 16:7-11", "overview": "Jesus says it's advantageous for Him to go so the Helper can come. The Spirit convicts the world concerning sin, righteousness, and judgment.", "reflection": "How does the Spirit convict of sin? What is His role regarding righteousness and judgment? When have you experienced His conviction?", "prayer": "Thank God for the Spirit's convicting work and ask for sensitivity to His voice."},
            {"day": 3, "passage": "{{translation}}: Acts 1:8", "overview": "Jesus promises believers will receive power when the Holy Spirit comes upon them, making them witnesses in Jerusalem, Judea, Samaria, and to the end of the earth.", "reflection": "How does the Spirit give power? What does being His witness mean? Where is He sending you?", "prayer": "Ask the Holy Spirit to empower you to be Jesus' witness wherever you go."},
            {"day": 4, "passage": "{{translation}}: Romans 8:26-27", "overview": "Paul teaches that the Spirit helps in weakness, interceding with groanings too deep for words. He intercedes for the saints according to God's will.", "reflection": "How does the Spirit help your weakness? What does His intercession mean? How does this comfort you?", "prayer": "Thank the Spirit for interceding for you and trust His prayers on your behalf."},
            {"day": 5, "passage": "{{translation}}: 1 Corinthians 12:4-11", "overview": "Paul describes varieties of gifts, service, and activities—all empowered by the same Spirit who apportions to each individually as He wills for the common good.", "reflection": "What spiritual gifts has the Spirit given you? How do you use them for the common good? How does diversity of gifts reflect unity?", "prayer": "Thank the Spirit for your gifts and ask how to use them better for God's glory."},
            {"day": 6, "passage": "{{translation}}: Galatians 5:22-23", "overview": "Paul lists the fruit of the Spirit: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control. This fruit evidences the Spirit's transforming work.", "reflection": "Which fruit is most evident in you? Which needs cultivation? How does the Spirit produce this fruit?", "prayer": "Ask the Spirit to produce His fruit abundantly in your life."},
            {"day": 7, "passage": "{{translation}}: Ephesians 5:18", "overview": "Paul commands believers not to be drunk with wine but be filled with the Spirit. Being Spirit-filled should characterize believers' lives.", "reflection": "What does being filled with the Spirit mean? How is this like or unlike drunkenness? How do you stay filled?", "prayer": "Ask to be continually filled with the Holy Spirit, yielding control to Him."}
        ]
    },

    "the_mission_of_the_church.json": {
        "title": "The Mission of the Church",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Matthew 28:18-20", "overview": "Jesus commissions His disciples to make disciples of all nations, baptizing and teaching them to observe all His commands. He promises His presence always.", "reflection": "What is the Great Commission? How are you making disciples? What does Jesus' presence with you mean?", "prayer": "Ask God to make you a disciple-maker and help you obey the Great Commission."},
            {"day": 2, "passage": "{{translation}}: Acts 1:8", "overview": "Jesus promises His disciples will receive power when the Holy Spirit comes and be His witnesses in Jerusalem, Judea, Samaria, and to the end of the earth.", "reflection": "Where is your Jerusalem? How does the Spirit empower witness? How far does your witness reach?", "prayer": "Ask the Spirit to empower you to witness both locally and to the ends of the earth."},
            {"day": 3, "passage": "{{translation}}: Acts 2:42-47", "overview": "The early church devoted themselves to teaching, fellowship, breaking bread, and prayer. They shared possessions, worshiped together, enjoyed favor with people, and the Lord added to their number daily.", "reflection": "How do these elements characterize your church? What does devotion to apostles' teaching mean? How does community life reflect the gospel?", "prayer": "Pray for your church to embody these characteristics and grow as the early church did."},
            {"day": 4, "passage": "{{translation}}: Ephesians 4:11-16", "overview": "Christ gave apostles, prophets, evangelists, shepherds, and teachers to equip the saints for ministry, building up the body until all reach unity, maturity, and the fullness of Christ.", "reflection": "What is the purpose of church leaders? How are you being equipped for ministry? What does maturity in Christ look like?", "prayer": "Thank God for leaders who equip you and pray for growth toward maturity in Christ."},
            {"day": 5, "passage": "{{translation}}: 1 Corinthians 12:12-27", "overview": "Paul compares the church to a body with many members. All are necessary; none can say they don't belong or aren't needed. If one suffers, all suffer; if one is honored, all rejoice.", "reflection": "What is your role in the body? How do you value others' roles? How do you share in others' joys and sufferings?", "prayer": "Thank God for your place in the body and pray for unity and mutual care."},
            {"day": 6, "passage": "{{translation}}: 1 Peter 2:9-10", "overview": "Peter declares believers are a chosen race, royal priesthood, holy nation, God's possession, called to proclaim His excellencies. Once not a people, now God's people.", "reflection": "What does being a royal priesthood mean? How do you proclaim God's excellencies? What difference does being God's people make?", "prayer": "Thank God for making you His possession and help you proclaim His greatness."},
            {"day": 7, "passage": "{{translation}}: Revelation 7:9-10", "overview": "John sees a great multitude from every nation, tribe, people, and language standing before the throne worshiping God and the Lamb. This is the church's destiny.", "reflection": "How does this vision inspire the church's mission? What does worshiping with all nations mean? How does this hope motivate you?", "prayer": "Thank God for the promise that people from every nation will worship Him forever."}
        ]
    },

    "the_names_of_god.json": {
        "title": "The Names of God",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Genesis 1:1", "overview": "The Bible begins with 'Elohim' (God) creating the heavens and earth. This name emphasizes God's power, might, and supreme authority as Creator.", "reflection": "What does God as Creator mean to you? How does His creative power affect your view of Him? What has He created in your life?", "prayer": "Worship Elohim, the all-powerful Creator of heaven and earth."},
            {"day": 2, "passage": "{{translation}}: Genesis 22:13-14", "overview": "After God provides a ram instead of Isaac, Abraham names the place 'Yahweh-Yireh' (The LORD Will Provide). God sees needs and provides for His people.", "reflection": "How has God provided for you? What needs are you trusting Him to meet? What does God's provision teach about His character?", "prayer": "Thank Yahweh-Yireh for His faithful provision and trust Him with current needs."},
            {"day": 3, "passage": "{{translation}}: Exodus 15:26", "overview": "After healing bitter waters, God reveals Himself as 'Yahweh-Rapha' (The LORD Who Heals). He promises health to those who obey Him.", "reflection": "What healing do you need from God? How has He healed you? What does God as healer mean beyond physical healing?", "prayer": "Ask Yahweh-Rapha to heal you physically, emotionally, and spiritually."},
            {"day": 4, "passage": "{{translation}}: Psalm 23:1", "overview": "David declares 'Yahweh-Rohi' (The LORD is my Shepherd), trusting God's guidance, provision, and protection. A shepherd cares intimately for his sheep.", "reflection": "How is God your Shepherd? Where is He leading you? How do you experience His care and protection?", "prayer": "Thank Yahweh-Rohi for shepherding you and ask Him to guide you today."},
            {"day": 5, "passage": "{{translation}}: Judges 6:24", "overview": "After encountering God's angel, Gideon builds an altar named 'Yahweh-Shalom' (The LORD is Peace). Even in turmoil, God gives peace.", "reflection": "Where do you need God's peace? How does knowing God as peace affect anxiety? What peace has He given you?", "prayer": "Ask Yahweh-Shalom to fill you with His peace in every circumstance."},
            {"day": 6, "passage": "{{translation}}: Jeremiah 23:5-6", "overview": "God promises a righteous Branch who will be called 'Yahweh-Tsidkenu' (The LORD Our Righteousness). This prophecy points to Christ, our righteousness.", "reflection": "How is Jesus your righteousness? What does it mean to have righteousness not your own? How does this free you?", "prayer": "Thank Yahweh-Tsidkenu for being your righteousness through Jesus Christ."},
            {"day": 7, "passage": "{{translation}}: Ezekiel 48:35", "overview": "Ezekiel's vision of the restored city ends with its name: 'Yahweh-Shammah' (The LORD is There). God's presence defines His people's ultimate blessing.", "reflection": "What does God's presence mean to you? How do you experience Him being 'there'? How does His presence change everything?", "prayer": "Thank Yahweh-Shammah for His presence with you and worship Him as Emmanuel, God with us."}
        ]
    },

    "understanding_sanctification.json": {
        "title": "Understanding Sanctification",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: 1 Thessalonians 4:3", "overview": "Paul declares that God's will is your sanctification. Sanctification—being set apart for God and made holy—is central to God's purpose for believers.", "reflection": "What is sanctification? How is it God's will for you? What does being set apart mean?", "prayer": "Ask God to sanctify you completely according to His will."},
            {"day": 2, "passage": "{{translation}}: Hebrews 10:10", "overview": "The author declares believers have been sanctified through the offering of Jesus Christ's body once for all. Sanctification is accomplished through Christ's sacrifice.", "reflection": "How were you sanctified? What did Christ's sacrifice accomplish? How is sanctification both accomplished and ongoing?", "prayer": "Thank Jesus for sanctifying you through His once-for-all sacrifice."},
            {"day": 3, "passage": "{{translation}}: 2 Thessalonians 2:13", "overview": "Paul thanks God for choosing believers for salvation through sanctification by the Spirit and belief in the truth. The Spirit works sanctification in those who believe.", "reflection": "What is the Spirit's role in sanctification? How does belief in truth sanctify? How do you cooperate with the Spirit's work?", "prayer": "Thank God for choosing you and ask the Spirit to continue His sanctifying work."},
            {"day": 4, "passage": "{{translation}}: Romans 6:19", "overview": "Paul instructs believers to present their members as slaves to righteousness leading to sanctification. Sanctification requires active presentation of ourselves to God.", "reflection": "What does presenting yourself to righteousness mean? How is sanctification progressive? What areas need to be presented to God?", "prayer": "Present yourself fully to God as a slave to righteousness leading to sanctification."},
            {"day": 5, "passage": "{{translation}}: 2 Corinthians 7:1", "overview": "Paul urges believers to cleanse themselves from every defilement of body and spirit, bringing holiness to completion in the fear of God.", "reflection": "What defilements need cleansing? How do you bring holiness to completion? What role does fear of God play?", "prayer": "Ask God to cleanse you from all defilement and complete your sanctification."},
            {"day": 6, "passage": "{{translation}}: John 17:17", "overview": "Jesus prays for His disciples: 'Sanctify them in the truth; your word is truth.' God's Word is the means by which believers are sanctified.", "reflection": "How does God's Word sanctify you? What truth is transforming you? How much time do you spend in the Word?", "prayer": "Ask God to sanctify you through His Word and help you treasure it."},
            {"day": 7, "passage": "{{translation}}: 1 Thessalonians 5:23-24", "overview": "Paul prays that the God of peace would sanctify believers completely—spirit, soul, and body—kept blameless until Christ's coming. He who calls is faithful and will do it.", "reflection": "What does complete sanctification mean? How is God faithful to sanctify you? What hope does this give?", "prayer": "Trust God's faithfulness to sanctify you completely until Christ returns."}
        ]
    },

    "understanding_the_prophets.json": {
        "title": "Understanding the Prophets",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Jeremiah 1:4-10", "overview": "God calls Jeremiah before birth to be a prophet to nations. Though young, Jeremiah is appointed to uproot and tear down, destroy and overthrow, build and plant.", "reflection": "What is a prophet's role? How does God call and equip prophets? What does Jeremiah's calling teach about God's purposes?", "prayer": "Thank God for speaking through prophets and ask Him to help you hear His word."},
            {"day": 2, "passage": "{{translation}}: Isaiah 6:1-8", "overview": "Isaiah sees the Lord on His throne, experiences conviction of sin, receives cleansing from a burning coal, and volunteers when God asks who will go for Him.", "reflection": "What does Isaiah's vision reveal about God? How does seeing God's holiness produce conviction? How do you respond to God's call?", "prayer": "Worship God's holiness and respond to His call: 'Here am I! Send me.'"},
            {"day": 3, "passage": "{{translation}}: Amos 5:21-24", "overview": "Through Amos, God rejects Israel's religious festivals because they neglect justice. He desires justice to roll down like waters and righteousness like an ever-flowing stream.", "reflection": "What do the prophets emphasize? How can religious activity substitute for justice? What does God truly desire?", "prayer": "Ask God to help you match worship with pursuit of justice and righteousness."},
            {"day": 4, "passage": "{{translation}}: Micah 6:8", "overview": "Micah summarizes what God requires: to do justice, love kindness, and walk humbly with God. This encapsulates the prophetic message.", "reflection": "How do you do justice and love mercy? What does walking humbly with God mean? How do the prophets challenge you?", "prayer": "Ask God to help you do justice, love kindness, and walk humbly with Him."},
            {"day": 5, "passage": "{{translation}}: Isaiah 53:3-6", "overview": "Isaiah prophesies about the Suffering Servant who bears our griefs, carries our sorrows, is pierced for our transgressions, crushed for our iniquities. The LORD lays on Him our iniquity.", "reflection": "How is this fulfilled in Jesus? What does the Suffering Servant accomplish? How does prophecy point to Christ?", "prayer": "Thank Jesus for fulfilling Isaiah's prophecy and bearing your sins."},
            {"day": 6, "passage": "{{translation}}: Ezekiel 36:26-27", "overview": "God promises a new heart and new spirit, removing the heart of stone and giving a heart of flesh. He will put His Spirit within them, causing them to walk in His statutes.", "reflection": "What does a new heart mean? How has God given you His Spirit? How does the Spirit enable obedience?", "prayer": "Thank God for giving you a new heart and His Spirit within you."},
            {"day": 7, "passage": "{{translation}}: Joel 2:28-29", "overview": "God promises to pour out His Spirit on all flesh—sons and daughters prophesying, old men dreaming dreams, young men seeing visions, even on servants.", "reflection": "How was this fulfilled at Pentecost? What does the Spirit being poured out mean? How do you experience the Spirit's work?", "prayer": "Thank God for pouring out His Spirit and ask to be filled afresh."}
        ]
    },

    "walk_of_discipleship.json": {
        "title": "Walk of Discipleship",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Luke 9:23", "overview": "Jesus declares that if anyone would come after Him, he must deny himself, take up his cross daily, and follow. Discipleship requires self-denial and daily commitment.", "reflection": "What does denying yourself mean? What is your cross? How do you take it up daily?", "prayer": "Ask Jesus for grace to deny yourself, take up your cross, and follow Him daily."},
            {"day": 2, "passage": "{{translation}}: John 15:5", "overview": "Jesus declares He is the vine and believers are branches. Whoever abides in Him and He in them bears much fruit, for apart from Him they can do nothing.", "reflection": "What does abiding in Jesus mean? How do you remain connected to the vine? What fruit comes from abiding?", "prayer": "Ask Jesus to teach you to abide in Him and bear much fruit."},
            {"day": 3, "passage": "{{translation}}: John 13:34-35", "overview": "Jesus gives a new commandment: love one another as He has loved them. By this love, all will know they are His disciples.", "reflection": "How has Jesus loved you? How do you love others with His love? What does this love reveal?", "prayer": "Ask God to fill you with Jesus' love for others that identifies you as His disciple."},
            {"day": 4, "passage": "{{translation}}: Matthew 28:19-20", "overview": "Jesus commissions disciples to make disciples of all nations, baptizing and teaching them to observe all He commanded. He promises His presence always.", "reflection": "How are you making disciples? What does teaching obedience mean? How does Jesus' presence encourage you?", "prayer": "Commit to making disciples and thank Jesus for His constant presence."},
            {"day": 5, "passage": "{{translation}}: Luke 14:26-27", "overview": "Jesus teaches that discipleship requires loving Him more than family, even one's own life. Whoever doesn't bear his cross and come after Jesus cannot be His disciple.", "reflection": "What does this priority mean? Is Jesus first in your life? What might you need to love less?", "prayer": "Ask Jesus to be first above all other loves and relationships."},
            {"day": 6, "passage": "{{translation}}: Mark 8:34-35", "overview": "Jesus teaches that to save your life, you must lose it; whoever loses his life for Jesus and the gospel will save it. True discipleship involves sacrifice.", "reflection": "What does losing your life mean? What are you holding onto? How do you lose your life for Jesus?", "prayer": "Ask God for courage to lose your life for Jesus and find true life in Him."},
            {"day": 7, "passage": "{{translation}}: Philippians 3:7-8", "overview": "Paul counts everything as loss compared to the surpassing worth of knowing Christ Jesus his Lord. For His sake, Paul has suffered the loss of all things, counting them as rubbish.", "reflection": "What is worth compared to knowing Christ? What have you given up for Him? What still competes with Him?", "prayer": "Ask God to help you count everything as loss compared to knowing Jesus."}
        ]
    },

    "wisdom_from_proverbs.json": {
        "title": "Wisdom from Proverbs",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Proverbs 1:7", "overview": "Solomon declares the fear of the Lord is the beginning of knowledge; fools despise wisdom and instruction. True wisdom starts with proper reverence for God.", "reflection": "What does fearing the Lord mean? How is it the foundation of wisdom? What makes someone a fool?", "prayer": "Ask God for a healthy fear of Him that leads to true wisdom."},
            {"day": 2, "passage": "{{translation}}: Proverbs 3:5-6", "overview": "Trust in the Lord with all your heart; don't lean on your own understanding. In all your ways acknowledge Him, and He will make straight your paths.", "reflection": "What does trusting God with all your heart mean? Where do you rely on your own understanding? How do you acknowledge God?", "prayer": "Commit to trusting God fully and acknowledging Him in all your ways."},
            {"day": 3, "passage": "{{translation}}: Proverbs 4:23", "overview": "Above all else, guard your heart, for from it flow the springs of life. The heart is the wellspring of all we do.", "reflection": "What threatens your heart? How do you guard it? What flows from your heart?", "prayer": "Ask God to help you vigilantly guard your heart and keep it pure."},
            {"day": 4, "passage": "{{translation}}: Proverbs 16:18", "overview": "Pride goes before destruction, and a haughty spirit before a fall. Pride sets up inevitable collapse.", "reflection": "Where is pride showing up in your life? What destruction can pride cause? How do you cultivate humility?", "prayer": "Confess any pride and ask God to humble you before you fall."},
            {"day": 5, "passage": "{{translation}}: Proverbs 18:21", "overview": "Death and life are in the power of the tongue; those who love it will eat its fruits. Words have tremendous power.", "reflection": "How have you used your tongue lately? What fruit have your words produced? How can you speak life?", "prayer": "Ask God to control your tongue and help you speak words of life."},
            {"day": 6, "passage": "{{translation}}: Proverbs 27:17", "overview": "Iron sharpens iron, and one man sharpens another. Believers need mutual accountability and encouragement for spiritual growth.", "reflection": "Who sharpens you? Who are you sharpening? What does this sharpening look like?", "prayer": "Thank God for those who sharpen you and pray for wisdom to sharpen others."},
            {"day": 7, "passage": "{{translation}}: Proverbs 31:30", "overview": "Charm is deceitful and beauty is vain, but a woman who fears the Lord is to be praised. Character matters more than appearance.", "reflection": "What do you value—outward beauty or inner character? How do you cultivate fear of the Lord? What is praiseworthy?", "prayer": "Ask God to help you value what He values and cultivate godly character."}
        ]
    }
}

# Create files
comp_dir = r"c:\Users\Demetrius\Documents\sword-drill\public\bible_study_plans\comprehensive"
for filename, content in comprehensive_plans.items():
    filepath = os.path.join(comp_dir, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(content, f, indent=2, ensure_ascii=False)
    print(f"Created {filename}")

print(f"\nCompleted {len(comprehensive_plans)} comprehensive plans")
print(f"TOTAL COMPREHENSIVE PLANS: 24")
print(f"\n✅ ALL BIBLE STUDY PLANS COMPLETE!")
print(f"   - 25 Short Plans (3-5 days each)")
print(f"   - 24 Comprehensive Plans (7-10 days each)")
