import json
import os

comprehensive_plans = {
    "end_times_overview.json": {
        "title": "End Times Overview",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Matthew 24:3-14", "overview": "Jesus describes signs before the end: false prophets, wars, famines, earthquakes, persecution. The gospel must be proclaimed to all nations before the end comes.", "reflection": "What signs of the end times do you see today? How should awareness of the end affect your life? How are you participating in proclaiming the gospel?", "prayer": "Pray for readiness for Christ's return and boldness in gospel proclamation."},
            {"day": 2, "passage": "{{translation}}: Matthew 24:29-31", "overview": "Jesus describes His return: cosmic signs, the Son of Man coming on clouds with power and glory, angels gathering the elect. His return will be unmistakable and glorious.", "reflection": "What does Jesus' return mean to you? How should you prepare? What comfort do you find in His promised return?", "prayer": "Express your longing for Jesus' return and ask Him to keep you ready."},
            {"day": 3, "passage": "{{translation}}: 1 Thessalonians 4:13-18", "overview": "Paul comforts believers about those who have died—at Christ's return, the dead in Christ will rise first, then living believers will be caught up together to meet the Lord in the air, forever with Him.", "reflection": "What hope does Christ's return give regarding death? How does this promise comfort you? How do you encourage others with these words?", "prayer": "Thank God for the hope of resurrection and eternal life with Christ."},
            {"day": 4, "passage": "{{translation}}: 1 Corinthians 15:51-58", "overview": "Paul reveals a mystery: at the last trumpet, the dead will be raised imperishable and the living will be changed. Death is swallowed up in victory through Jesus Christ.", "reflection": "What does being changed in a moment mean? How does resurrection hope affect how you live? How can you abound in the Lord's work?", "prayer": "Thank God for victory over death and commit to steadfast service until Christ returns."},
            {"day": 5, "passage": "{{translation}}: 2 Peter 3:8-14", "overview": "Peter explains that God's timing differs from ours—He is patient, not wanting any to perish. The day of the Lord will come like a thief, so believers should live holy and godly lives.", "reflection": "How does God's patience affect your view of His timing? What does waiting for new heavens and earth mean? How should you live in light of the coming day?", "prayer": "Thank God for His patience and pray for holiness as you wait for His return."},
            {"day": 6, "passage": "{{translation}}: Revelation 19:11-16", "overview": "John sees heaven opened and Jesus returning as King of kings and Lord of lords, riding a white horse, leading the armies of heaven, judging and making war in righteousness.", "reflection": "What does Jesus' role as conquering King mean? How does His return bring justice? How do you prepare for Him as judge and king?", "prayer": "Worship Jesus as King of kings and Lord of lords and long for His righteous reign."},
            {"day": 7, "passage": "{{translation}}: Revelation 21:1-5", "overview": "John sees a new heaven and new earth, the New Jerusalem descending, God dwelling with His people, wiping away every tear. Death, mourning, crying, and pain will be no more.", "reflection": "What does the new heaven and earth promise mean to you? How does God dwelling with you bring comfort? What suffering will finally end?", "prayer": "Thank God for the promise of new creation and His eternal presence with you."},
            {"day": 8, "passage": "{{translation}}: Revelation 22:12-17", "overview": "Jesus declares He is coming soon, bringing His recompense to repay each for what they have done. He is the Alpha and Omega. The Spirit and Bride say, 'Come!' Blessed are those who wash their robes.", "reflection": "What does Jesus' promise to come soon mean for how you live? How do you say 'Come, Lord Jesus'? How are you made ready?", "prayer": "Express your longing for Jesus' return: 'Come, Lord Jesus! Come quickly!'"}
        ]
    },

    "faith_of_abraham.json": {
        "title": "Faith of Abraham",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Genesis 12:1-4", "overview": "God calls Abram to leave his country and family for a land He will show him. Abram obeys by faith without knowing the destination, trusting God's promise.", "reflection": "When has God called you to step out in faith? How do you respond when you don't know the full plan? What does obedient faith look like?", "prayer": "Ask God for Abraham's faith to obey even when you don't see the full picture."},
            {"day": 2, "passage": "{{translation}}: Genesis 15:1-6", "overview": "God promises Abram countless descendants though he is childless. Abram believes the Lord, and God counts it to him as righteousness. Faith is credited as righteousness.", "reflection": "What impossible promises are you trusting God for? How is faith counted as righteousness? What does believing God mean?", "prayer": "Thank God for counting faith as righteousness and strengthen your trust in His promises."},
            {"day": 3, "passage": "{{translation}}: Genesis 17:1-8", "overview": "God establishes His covenant with Abraham, promising to make him the father of many nations and give his descendants the land of Canaan. Abraham's name is changed from Abram.", "reflection": "What does God's covenant reveal about His faithfulness? How does Abraham's name change reflect his identity? What covenant promises do you trust?", "prayer": "Thank God for His covenant faithfulness and for giving you a new identity in Christ."},
            {"day": 4, "passage": "{{translation}}: Genesis 22:1-18", "overview": "God tests Abraham by commanding him to sacrifice Isaac. Abraham obeys, trusting God to provide. God provides a ram and reaffirms His covenant promises because Abraham did not withhold his son.", "reflection": "How did Abraham's faith show itself in action? What has God asked you to surrender? How do you trust God to provide?", "prayer": "Ask God for faith to obey even when His commands seem impossible to understand."},
            {"day": 5, "passage": "{{translation}}: Romans 4:18-25", "overview": "Paul describes Abraham's faith—against hope he believed in hope, not weakened by considering his own body or Sarah's barrenness, fully convinced God could do what He promised.", "reflection": "How did Abraham believe against hope? What obstacles to God's promises do you focus on? How can you be fully convinced of God's power?", "prayer": "Pray for unwavering faith that believes God's promises despite circumstances."},
            {"day": 6, "passage": "{{translation}}: Hebrews 11:8-12", "overview": "The author praises Abraham's faith in obeying the call to an unknown place, dwelling in tents as a stranger, looking forward to the city whose designer and builder is God.", "reflection": "How did faith make Abraham a sojourner? What eternal city are you looking forward to? How does eternal perspective affect earthly living?", "prayer": "Ask God to help you live as a sojourner, longing for the eternal city He has prepared."},
            {"day": 7, "passage": "{{translation}}: Hebrews 11:17-19", "overview": "Abraham's faith was tested when offering Isaac. He reasoned that God could raise the dead, and figuratively speaking, he received Isaac back. Faith trusts God's ability beyond death.", "reflection": "How far does your faith trust God? What does believing God can raise the dead mean? How did Abraham's faith go beyond what seemed possible?", "prayer": "Pray for faith that trusts God's power even beyond death and impossibility."}
        ]
    },

    "fruit_of_the_spirit.json": {
        "title": "Fruit of the Spirit",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Galatians 5:22-23", "overview": "Paul lists the fruit of the Spirit: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control. These are the evidence of the Spirit's work in believers' lives.", "reflection": "Which fruit is most evident in your life? Which needs cultivation? How does the Spirit produce this fruit?", "prayer": "Ask the Spirit to produce His fruit abundantly in your life."},
            {"day": 2, "passage": "{{translation}}: 1 Corinthians 13:4-7", "overview": "Paul defines love—patient, kind, not envious or boastful, not arrogant or rude, not insisting on its own way, not irritable or resentful, rejoicing with truth, bearing, believing, hoping, enduring all things.", "reflection": "How does your love measure against this definition? Where do you fall short? What would it take to love like this?", "prayer": "Ask God to fill you with His love that is patient, kind, and enduring."},
            {"day": 3, "passage": "{{translation}}: Philippians 4:4-7", "overview": "Paul commands believers to rejoice in the Lord always, showing reasonableness, bringing everything to God in prayer with thanksgiving. The result is God's peace guarding hearts and minds.", "reflection": "How do you cultivate joy in the Lord? What does it mean to rejoice always? How does prayer with thanksgiving produce peace?", "prayer": "Pray for constant joy in the Lord and peace that guards your heart and mind."},
            {"day": 4, "passage": "{{translation}}: Colossians 3:12-14", "overview": "Paul instructs believers to put on compassionate hearts, kindness, humility, meekness, and patience, bearing with one another, forgiving as the Lord forgave, and above all, putting on love.", "reflection": "Which virtues do you need to 'put on' more intentionally? How do you bear with others? Why is love the greatest?", "prayer": "Ask God to clothe you with these virtues and make love your highest pursuit."},
            {"day": 5, "passage": "{{translation}}: James 3:17-18", "overview": "James describes wisdom from above as pure, peaceable, gentle, open to reason, full of mercy and good fruits, impartial and sincere. Righteousness is sown in peace by peacemakers.", "reflection": "What characteristics of heavenly wisdom do you see in your life? How can you be a peacemaker? What does sowing righteousness in peace mean?", "prayer": "Pray for wisdom from above that is pure, peaceable, and full of mercy."},
            {"day": 6, "passage": "{{translation}}: 1 Timothy 6:11", "overview": "Paul commands Timothy to pursue righteousness, godliness, faith, love, steadfastness, and gentleness. These virtues are to be actively pursued, not passively hoped for.", "reflection": "Which virtues are you actively pursuing? What does pursuit look like? How do you develop steadfastness and gentleness?", "prayer": "Commit to actively pursuing these godly virtues with the Spirit's help."},
            {"day": 7, "passage": "{{translation}}: Titus 2:11-12", "overview": "Paul teaches that God's grace trains us to renounce ungodliness and worldly passions, to live self-controlled, upright, and godly lives. Grace produces transformation, including self-control.", "reflection": "How does grace train you? What ungodliness needs to be renounced? How do you develop self-control?", "prayer": "Thank God for His grace and ask Him to train you in godliness and self-control."}
        ]
    },

    "god's_providence.json": {
        "title": "God's Providence",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Genesis 50:20", "overview": "Joseph tells his brothers that though they meant evil against him, God meant it for good, to bring about the saving of many lives. God works through even evil intentions.", "reflection": "When has God brought good from evil circumstances? How do you trust God's purposes in suffering? What does divine providence mean?", "prayer": "Thank God for working all things together for good, even when you don't understand."},
            {"day": 2, "passage": "{{translation}}: Romans 8:28", "overview": "Paul declares that for those who love God and are called according to His purpose, He works all things together for good. God sovereignly orchestrates circumstances for believers' benefit.", "reflection": "What difficult circumstances are you trusting God to use for good? How do you love God in the midst of trials? What is God's purpose for you?", "prayer": "Trust God to work all things together for your good according to His purpose."},
            {"day": 3, "passage": "{{translation}}: Proverbs 16:9", "overview": "Solomon writes that the heart of man plans his way, but the Lord establishes his steps. Human planning is subject to divine providence—God directs our paths.", "reflection": "How do you balance planning with trusting God? When has God redirected your plans? How do you submit your plans to God?", "prayer": "Ask God to establish your steps and direct your path according to His will."},
            {"day": 4, "passage": "{{translation}}: Matthew 10:29-31", "overview": "Jesus teaches that not even a sparrow falls to the ground apart from the Father, and believers are more valuable than many sparrows. God's providence extends to the smallest details.", "reflection": "How does God's care for sparrows comfort you? What details of your life are under God's care? How valuable are you to God?", "prayer": "Thank God for His detailed care over every aspect of your life."},
            {"day": 5, "passage": "{{translation}}: Ephesians 1:11", "overview": "Paul declares that believers have obtained an inheritance, having been predestined according to the purpose of Him who works all things according to the counsel of His will.", "reflection": "What does it mean that God works all things according to His will? How does God's sovereignty comfort you? What inheritance awaits you?", "prayer": "Praise God for His sovereign control over all things and for securing your inheritance."},
            {"day": 6, "passage": "{{translation}}: Psalm 139:16", "overview": "David declares that God saw his unformed substance and in His book were written all the days that were formed for him, when as yet there were none. God ordained every day before they came to be.", "reflection": "What does it mean that God ordained your days? How does this truth affect your view of life's events? How do you trust God's plan for your days?", "prayer": "Thank God for ordaining all your days and trust His plan for your life."},
            {"day": 7, "passage": "{{translation}}: Isaiah 46:9-10", "overview": "God declares the end from the beginning, proclaiming things not yet done, saying His counsel shall stand and He will accomplish all His purpose. God's plans cannot be thwarted.", "reflection": "What does God's declaration of the end from the beginning mean? How do you trust that God's counsel will stand? What purposes of God do you see unfolding?", "prayer": "Worship God for His sovereignty and unchangeable purposes that will surely come to pass."}
        ]
    },

    "gospel_foundations.json": {
        "title": "Gospel Foundations",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Romans 3:23", "overview": "Paul declares that all have sinned and fall short of the glory of God. The gospel begins with the universal problem: human sinfulness and separation from God's glory.", "reflection": "How do you understand your own sinfulness? What does falling short of God's glory mean? Why is recognizing sin essential to the gospel?", "prayer": "Confess your sinfulness and thank God for not leaving you in that state."},
            {"day": 2, "passage": "{{translation}}: Romans 6:23", "overview": "Paul states that the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord. Sin earns death; grace gives life.", "reflection": "What does it mean that sin's wage is death? How is eternal life a gift, not wages? How have you received this gift?", "prayer": "Thank God for the gift of eternal life and for sending Jesus to pay sin's penalty."},
            {"day": 3, "passage": "{{translation}}: Romans 5:8", "overview": "Paul reveals that God demonstrates His own love for us in that while we were still sinners, Christ died for us. God's love acted while we were His enemies.", "reflection": "How does Christ's death demonstrate God's love? What does it mean that He died while you were still a sinner? How does this shape your understanding of grace?", "prayer": "Marvel at God's love shown in Christ's death for you while you were still a sinner."},
            {"day": 4, "passage": "{{translation}}: 1 Corinthians 15:3-4", "overview": "Paul summarizes the gospel: Christ died for our sins according to the Scriptures, was buried, and was raised on the third day according to the Scriptures. These are the gospel essentials.", "reflection": "Why is Christ's death, burial, and resurrection the core of the gospel? How do the Scriptures testify to these events? What difference does the resurrection make?", "prayer": "Thank Jesus for dying for your sins, being buried, and rising victoriously from the dead."},
            {"day": 5, "passage": "{{translation}}: John 3:16", "overview": "Jesus declares that God so loved the world that He gave His only Son, that whoever believes in Him should not perish but have eternal life. Belief in Jesus is the means of salvation.", "reflection": "What does God's love giving His Son mean? How do you believe in Jesus? What does eternal life mean to you?", "prayer": "Thank God for loving you enough to give His only Son for your salvation."},
            {"day": 6, "passage": "{{translation}}: Ephesians 2:8-9", "overview": "Paul explains that salvation is by grace through faith, not from works, so no one can boast. It is God's gift. Works cannot earn salvation—only grace received by faith saves.", "reflection": "How do you understand grace? What works are you tempted to rely on? Why is salvation by grace alone important?", "prayer": "Thank God for the gift of salvation by grace through faith, not by works."},
            {"day": 7, "passage": "{{translation}}: Romans 10:9-10", "overview": "Paul teaches that if you confess with your mouth that Jesus is Lord and believe in your heart that God raised Him from the dead, you will be saved. Belief in the heart leads to righteousness; confession leads to salvation.", "reflection": "Have you confessed Jesus as Lord? What does believing in His resurrection mean? How do belief and confession work together?", "prayer": "Confess Jesus as Lord and thank God for raising Him from the dead for your salvation."},
            {"day": 8, "passage": "{{translation}}: Acts 16:30-31", "overview": "When the Philippian jailer asks what he must do to be saved, Paul and Silas answer: 'Believe in the Lord Jesus, and you will be saved.' Salvation comes through faith in Jesus.", "reflection": "What does believing in the Lord Jesus mean? How simple is the gospel? How can you share this message with others?", "prayer": "Thank God for the simplicity of the gospel: believe in Jesus and be saved."}
        ]
    }
}

# Create files
comp_dir = r"c:\Users\Demetrius\Documents\sword-drill\public\bible_study_plans\comprehensive"
for filename, content in comprehensive_plans.items():
    filepath = os.path.join(comp_dir, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(content, f, indent=2, ensure_ascii=False)
    print(f"Created {filename}")

print(f"\nCompleted {len(comprehensive_plans)} more comprehensive plans")
