import json
import os

comprehensive_plans = {
    "holiness_unto_the_lord.json": {
        "title": "Holiness Unto the Lord",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Leviticus 11:44-45", "overview": "God commands Israel to be holy because He is holy. Holiness is rooted in God's character and reflects His people's identity as those brought out of Egypt to be His possession.", "reflection": "What does it mean to be holy? How does God's holiness motivate yours? How do you pursue holiness?", "prayer": "Ask God to make you holy as He is holy and help you reflect His character."},
            {"day": 2, "passage": "{{translation}}: 1 Peter 1:14-16", "overview": "Peter calls believers to be holy in all conduct, not conformed to former passions. As obedient children, they should be holy because God is holy.", "reflection": "What former passions do you need to leave behind? How do you pursue holiness in all conduct? What does obedience have to do with holiness?", "prayer": "Pray for transformation from old patterns and growth in holiness in every area."},
            {"day": 3, "passage": "{{translation}}: Hebrews 12:14", "overview": "The author urges believers to strive for peace with everyone and for holiness without which no one will see the Lord. Holiness is essential for seeing God.", "reflection": "How do you pursue holiness? Why is holiness necessary to see the Lord? How do peace and holiness connect?", "prayer": "Ask God to help you strive for holiness and make peace with everyone."},
            {"day": 4, "passage": "{{translation}}: 2 Corinthians 7:1", "overview": "Paul urges believers to cleanse themselves from every defilement of body and spirit, bringing holiness to completion in the fear of God. Holiness involves active purification.", "reflection": "What defilements need cleansing in your life? How do you bring holiness to completion? What role does fear of God play?", "prayer": "Confess any defilement and ask God to help you pursue complete holiness."},
            {"day": 5, "passage": "{{translation}}: 1 Thessalonians 4:3-7", "overview": "Paul declares that God's will is your sanctification—abstaining from sexual immorality, controlling your body in holiness and honor. God calls us to holiness, not impurity.", "reflection": "What does sanctification mean? How do you control your body in holiness? What impurity needs to be rejected?", "prayer": "Thank God for calling you to holiness and pray for purity in all areas."},
            {"day": 6, "passage": "{{translation}}: Romans 6:19-22", "overview": "Paul instructs believers to present their members as slaves to righteousness leading to sanctification. Now set free from sin and enslaved to God, they have fruit leading to sanctification and eternal life.", "reflection": "What does slavery to righteousness look like? How do you present yourself to God? What fruit of sanctification do you see?", "prayer": "Present yourself fully to God as a slave to righteousness leading to holiness."},
            {"day": 7, "passage": "{{translation}}: Ephesians 1:4", "overview": "Paul declares that God chose believers in Christ before the foundation of the world to be holy and blameless before Him in love. Holiness is God's eternal plan for His people.", "reflection": "What does being chosen for holiness mean? How does God's eternal purpose affect your pursuit of holiness? How do love and holiness connect?", "prayer": "Thank God for choosing you to be holy and blameless before Him in love."}
        ]
    },

    "hope_of_resurrection.json": {
        "title": "Hope of Resurrection",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: 1 Corinthians 15:12-19", "overview": "Paul argues that if there is no resurrection, Christ was not raised, preaching is in vain, faith is futile, and believers are most to be pitied. Resurrection is essential to Christian faith.", "reflection": "Why is resurrection central to Christianity? What would change if there were no resurrection? How does resurrection hope affect your life?", "prayer": "Thank God that Christ has been raised and your faith is not in vain."},
            {"day": 2, "passage": "{{translation}}: 1 Corinthians 15:20-23", "overview": "Paul declares Christ as the firstfruits of those who have fallen asleep. As in Adam all die, so in Christ all will be made alive. Christ's resurrection guarantees ours.", "reflection": "What does Christ being firstfruits mean? How does Adam bring death and Christ bring life? When will you be made alive?", "prayer": "Thank Jesus for being the firstfruits and guaranteeing your resurrection."},
            {"day": 3, "passage": "{{translation}}: 1 Corinthians 15:35-44", "overview": "Paul explains the resurrection body: sown in dishonor, raised in glory; sown in weakness, raised in power; sown a natural body, raised a spiritual body. Resurrection transforms.", "reflection": "What will your resurrection body be like? How is it different from your current body? What does resurrection in power mean?", "prayer": "Thank God for the promise of a glorified resurrection body."},
            {"day": 4, "passage": "{{translation}}: 1 Corinthians 15:51-57", "overview": "Paul reveals that the dead will be raised imperishable and living believers will be changed. Death is swallowed up in victory. Thanks be to God who gives victory through Jesus Christ.", "reflection": "What does victory over death mean? How does this hope affect how you face death? What does being changed in a moment mean?", "prayer": "Thank God for victory over death through Jesus Christ."},
            {"day": 5, "passage": "{{translation}}: John 11:25-26", "overview": "Jesus declares He is the resurrection and the life. Whoever believes in Him will live even though they die, and whoever lives and believes in Him will never die.", "reflection": "How is Jesus the resurrection and the life? What does it mean to never die? Do you believe this?", "prayer": "Thank Jesus for being your resurrection and life, conquering death forever."},
            {"day": 6, "passage": "{{translation}}: Romans 8:11", "overview": "Paul teaches that if the Spirit of Him who raised Jesus from the dead dwells in you, He will give life to your mortal bodies through His Spirit who dwells in you.", "reflection": "How does the Spirit give life? What does future bodily resurrection mean? How does the Spirit's presence now connect to future resurrection?", "prayer": "Thank God for the Spirit dwelling in you and guaranteeing your resurrection."},
            {"day": 7, "passage": "{{translation}}: 1 Thessalonians 4:13-14", "overview": "Paul encourages believers not to grieve like those without hope. Since Jesus died and rose again, God will bring with Him those who have fallen asleep in Jesus.", "reflection": "How is Christian grief different? What hope do you have regarding death? How does Jesus' resurrection guarantee yours?", "prayer": "Thank God for resurrection hope that transforms how you face death and loss."}
        ]
    },

    "kingdom_parables.json": {
        "title": "Kingdom Parables",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Matthew 13:1-9, 18-23", "overview": "Jesus tells the parable of the sower. Seed falls on different soils—path, rocky ground, thorns, and good soil—representing different responses to God's word. Only good soil produces fruit.", "reflection": "What kind of soil is your heart? What prevents the word from bearing fruit in your life? How can you be good soil?", "prayer": "Ask God to make your heart good soil that receives His word and bears much fruit."},
            {"day": 2, "passage": "{{translation}}: Matthew 13:24-30, 36-43", "overview": "Jesus tells of wheat and weeds growing together until harvest. The field is the world, good seed are sons of the kingdom, weeds are sons of the evil one. Judgment comes at harvest.", "reflection": "What does this parable teach about coexistence of good and evil? How should you live knowing judgment is coming? What comfort does final judgment bring?", "prayer": "Thank God for patience with the world and pray for readiness for the final harvest."},
            {"day": 3, "passage": "{{translation}}: Matthew 13:31-32", "overview": "Jesus compares the kingdom to a mustard seed—the smallest seed that grows into the largest garden plant, sheltering birds. The kingdom starts small but grows immensely.", "reflection": "How does the kingdom start small? What growth have you seen? How does the kingdom provide shelter?", "prayer": "Thank God for the kingdom's growth from small beginnings to great expansion."},
            {"day": 4, "passage": "{{translation}}: Matthew 13:33", "overview": "Jesus likens the kingdom to leaven that a woman hid in three measures of flour until all was leavened. The kingdom permeates and transforms everything it touches.", "reflection": "How does the kingdom spread like leaven? How has the kingdom permeated your life? What transformation has it brought?", "prayer": "Ask God to let His kingdom permeate every area of your life."},
            {"day": 5, "passage": "{{translation}}: Matthew 13:44", "overview": "Jesus compares the kingdom to treasure hidden in a field. A man finds it, hides it, and in joy sells all he has to buy that field. The kingdom is worth everything.", "reflection": "What does discovering the kingdom mean? What have you given up for the kingdom? What joy comes from finding this treasure?", "prayer": "Thank God for the treasure of the kingdom and ask for willingness to give everything for it."},
            {"day": 6, "passage": "{{translation}}: Matthew 13:45-46", "overview": "Jesus likens the kingdom to a merchant searching for fine pearls. Finding one of great value, he sells all he has to purchase it. The kingdom is the pearl of greatest value.", "reflection": "How valuable is the kingdom to you? What have you sacrificed for it? What makes it worth everything?", "prayer": "Ask God to help you value the kingdom above all earthly possessions."},
            {"day": 7, "passage": "{{translation}}: Matthew 13:47-50", "overview": "Jesus compares the kingdom to a net gathering fish of every kind. The good are kept; the bad are thrown away. Angels will separate the evil from the righteous at the end of the age.", "reflection": "What does this parable teach about final judgment? How should this motivate holy living? What comfort or warning does this bring?", "prayer": "Pray for readiness for judgment and that you would be found among the righteous."}
        ]
    },

    "letters_of_paul.json": {
        "title": "Letters of Paul",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Romans 1:16-17", "overview": "Paul declares the gospel as God's power for salvation to everyone who believes. In it God's righteousness is revealed from faith for faith—the righteous shall live by faith.", "reflection": "Why is the gospel God's power? What does righteousness by faith mean? How do you live by faith daily?", "prayer": "Thank God for the gospel's power and help you live by faith."},
            {"day": 2, "passage": "{{translation}}: Galatians 2:20", "overview": "Paul declares he has been crucified with Christ and no longer lives, but Christ lives in him. The life he now lives is by faith in the Son of God who loved him and gave Himself for him.", "reflection": "What does being crucified with Christ mean? How does Christ live in you? How do you live by faith in Him?", "prayer": "Thank Jesus for loving you and giving Himself for you, and pray that He would live through you."},
            {"day": 3, "passage": "{{translation}}: Philippians 1:21", "overview": "Paul declares that for him to live is Christ and to die is gain. His entire existence centers on Christ—living for Him is purpose; dying to be with Him is gain.", "reflection": "Is Christ your life? What would it mean for Christ to be your life? How do you view death?", "prayer": "Ask God to make Christ the center and purpose of your life."},
            {"day": 4, "passage": "{{translation}}: Colossians 1:15-20", "overview": "Paul describes Christ's supremacy: image of the invisible God, firstborn over creation, Creator of all things, head of the church, firstborn from the dead, reconciler through His blood.", "reflection": "What does Christ's supremacy mean to you? How is He first in your life? How has He reconciled you to God?", "prayer": "Worship Jesus for His supremacy over all creation and thank Him for reconciliation."},
            {"day": 5, "passage": "{{translation}}: Ephesians 2:1-10", "overview": "Paul describes salvation: dead in sins, made alive with Christ, raised and seated with Him, saved by grace through faith—not by works—created in Christ for good works God prepared.", "reflection": "How were you dead in sins? How has God made you alive? What good works has God prepared for you?", "prayer": "Thank God for making you alive in Christ and creating you for good works."},
            {"day": 6, "passage": "{{translation}}: 1 Corinthians 13:1-13", "overview": "Paul's love chapter: without love, spiritual gifts mean nothing. Love is patient, kind, not envious or boastful. Faith, hope, and love remain, but the greatest is love.", "reflection": "How does your love measure against this standard? Why is love greater than other virtues? How can you grow in love?", "prayer": "Ask God to fill you with His love that is patient, kind, and never fails."},
            {"day": 7, "passage": "{{translation}}: 2 Timothy 3:16-17", "overview": "Paul declares all Scripture is breathed out by God and profitable for teaching, reproof, correction, and training in righteousness, that believers may be complete, equipped for every good work.", "reflection": "How is Scripture God-breathed? How do you use it for teaching and correction? How does Scripture equip you?", "prayer": "Thank God for His inspired Word and ask Him to use it to equip you fully."},
            {"day": 8, "passage": "{{translation}}: 1 Thessalonians 5:16-18", "overview": "Paul commands believers to rejoice always, pray without ceasing, and give thanks in all circumstances, for this is God's will for them in Christ Jesus.", "reflection": "How do you rejoice always? What does praying without ceasing mean? How can you be thankful in all circumstances?", "prayer": "Ask God to help you maintain constant joy, prayer, and thanksgiving."}
        ]
    },

    "life_of_david.json": {
        "title": "Life of David",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: 1 Samuel 16:1-13", "overview": "God rejects Saul and sends Samuel to anoint a new king. God chooses David, the youngest son, because the Lord looks at the heart, not outward appearance.", "reflection": "How does God's view differ from human judgment? What does God see in your heart? How did God prepare David for kingship?", "prayer": "Ask God to examine your heart and prepare you for His purposes."},
            {"day": 2, "passage": "{{translation}}: 1 Samuel 17:32-50", "overview": "David volunteers to fight Goliath, trusting God who delivered him from lion and bear. He defeats Goliath with a sling and stone, declaring the battle is the Lord's.", "reflection": "What giants do you face? How has God proven faithful in past battles? What does it mean that the battle is the Lord's?", "prayer": "Ask God for courage to face your giants, trusting that the battle belongs to Him."},
            {"day": 3, "passage": "{{translation}}: 1 Samuel 24:1-12", "overview": "David spares Saul's life in the cave, refusing to harm the Lord's anointed despite Saul's pursuit. David trusts God to establish justice rather than taking vengeance.", "reflection": "How do you respond to enemies? What does it mean to trust God for justice? When is it hard to leave vengeance to God?", "prayer": "Ask God for grace to trust Him for justice and refrain from personal vengeance."},
            {"day": 4, "passage": "{{translation}}: 2 Samuel 11:1-17", "overview": "David commits adultery with Bathsheba and arranges Uriah's death to cover his sin. Even a man after God's heart can fall into grievous sin when spiritually complacent.", "reflection": "What led to David's sin? What warning does this give? How do you guard against temptation and spiritual complacency?", "prayer": "Ask God to keep you from temptation and give you vigilance against sin."},
            {"day": 5, "passage": "{{translation}}: Psalm 51:1-12", "overview": "After Nathan confronts him, David's psalm of repentance acknowledges his sin, pleads for mercy, asks God to create a clean heart, and prays for restoration of salvation's joy.", "reflection": "How does David model repentance? What does a clean heart require? How do you experience restoration after sin?", "prayer": "Pray David's prayer: create a clean heart in you and restore the joy of salvation."},
            {"day": 6, "passage": "{{translation}}: 2 Samuel 7:8-16", "overview": "God establishes an everlasting covenant with David: his offspring will build a house for God's name, and God will establish his kingdom forever. This points to Jesus, David's ultimate descendant.", "reflection": "What does God's covenant with David promise? How is it fulfilled in Jesus? What does Jesus' eternal kingdom mean to you?", "prayer": "Thank God for His covenant faithfulness and for establishing Jesus' kingdom forever."},
            {"day": 7, "passage": "{{translation}}: 1 Kings 2:1-4", "overview": "David's final charge to Solomon emphasizes keeping God's ways, walking in His statutes, commandments, and testimonies, that God's promise to David's house might be established.", "reflection": "What was David's priority at the end of his life? What would you emphasize in a final charge? How do you walk in God's ways?", "prayer": "Commit to walking in God's ways and keeping His commandments all your days."}
        ]
    }
}

# Create files
comp_dir = r"c:\Users\Demetrius\Documents\sword-drill\public\bible_study_plans\comprehensive"
for filename, content in comprehensive_plans.items():
    filepath = os.path.join(comp_dir, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(content, f, indent=2, ensure_ascii=False)
    print(f"Created {filename}")

print(f"\nCompleted {len(comprehensive_plans)} more comprehensive plans")
print(f"Total so far: {5 + 5 + len(comprehensive_plans)} comprehensive plans")
