import json
import os

# Comprehensive plans (7-10 days each)
comprehensive_plans = {
    "biblical_justice.json": {
        "title": "Biblical Justice",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Micah 6:8", "overview": "Micah reveals what God requires: to do justice, love kindness, and walk humbly with God. Justice is central to God's character and His expectations for His people.", "reflection": "What does God require of you? How do you do justice in your context? How are justice, mercy, and humility connected?", "prayer": "Ask God to show you how to do justice, love mercy, and walk humbly with Him."},
            {"day": 2, "passage": "{{translation}}: Isaiah 1:16-17", "overview": "God calls His people to cease doing evil, learn to do good, seek justice, correct oppression, bring justice to the fatherless, and plead the widow's cause.", "reflection": "What evil needs to cease in your life? How can you seek justice for the oppressed? Who are the vulnerable you can advocate for?", "prayer": "Pray for eyes to see injustice and courage to stand up for the vulnerable."},
            {"day": 3, "passage": "{{translation}}: Amos 5:21-24", "overview": "God rejects religious ceremonies when His people neglect justice. He desires justice to roll down like waters and righteousness like an ever-flowing stream.", "reflection": "How might religious activity substitute for justice? What does justice 'rolling down' look like? Where is God calling you to prioritize justice?", "prayer": "Ask God to keep your worship authentic by matching it with pursuit of justice."},
            {"day": 4, "passage": "{{translation}}: Proverbs 31:8-9", "overview": "Scripture commands us to open our mouths for the mute, for the rights of all who are destitute, to judge righteously and plead the cause of the poor and needy.", "reflection": "Who cannot speak for themselves in your sphere? How can you advocate for the voiceless? What poor and needy are you ignoring?", "prayer": "Pray for boldness to speak up for those who cannot speak for themselves."},
            {"day": 5, "passage": "{{translation}}: Deuteronomy 10:17-19", "overview": "God executes justice for the fatherless and widow, loves the sojourner, and commands His people to love the sojourner as themselves, remembering they were sojourners in Egypt.", "reflection": "How does God's justice for the vulnerable affect your view of justice? Who are the 'sojourners' in your community? How can you love them?", "prayer": "Thank God for His justice and ask Him to help you extend it to the vulnerable."},
            {"day": 6, "passage": "{{translation}}: James 1:27", "overview": "Pure and undefiled religion before God is visiting orphans and widows in their affliction and keeping oneself unstained from the world. Justice and personal holiness go together.", "reflection": "How do you practice pure religion? What widows and orphans need your care? How does caring for the vulnerable relate to personal holiness?", "prayer": "Ask God to show you specific ways to care for orphans and widows while remaining holy."},
            {"day": 7, "passage": "{{translation}}: Matthew 23:23", "overview": "Jesus rebukes religious leaders for tithing minutely while neglecting weightier matters of the law: justice, mercy, and faithfulness. These should be done without neglecting the others.", "reflection": "What minor things do you focus on while neglecting justice? How do you balance details with weightier matters? What does Jesus' priority teach you?", "prayer": "Pray for wisdom to prioritize what matters most to God without neglecting any obedience."}
        ]
    },

    "book_of_james_deep_dive.json": {
        "title": "Book of James Deep Dive",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: James 1:1-8", "overview": "James introduces himself and immediately addresses trials, encouraging believers to count them as joy because testing produces steadfastness. Wisdom is available to those who ask in faith.", "reflection": "How do you respond to trials? What does counting trials as joy mean? When have you asked God for wisdom in faith?", "prayer": "Ask God for wisdom to navigate your current trials with joy and steadfastness."},
            {"day": 2, "passage": "{{translation}}: James 1:9-18", "overview": "James discusses the transience of wealth, the blessing of enduring temptation, and clarifies that God tempts no one—rather, He gives every good gift from above.", "reflection": "What is your relationship with wealth? How do you distinguish between trials and temptations? What good gifts has God given you?", "prayer": "Thank God for His perfect gifts and pray for endurance in temptation."},
            {"day": 3, "passage": "{{translation}}: James 1:19-27", "overview": "James warns against hearing without doing, emphasizes controlling the tongue, and defines pure religion as caring for orphans and widows while remaining unstained by the world.", "reflection": "Are you a doer or just a hearer? How well do you control your tongue? How do you practice pure religion?", "prayer": "Ask God to help you be a doer of the word, not just a hearer."},
            {"day": 4, "passage": "{{translation}}: James 2:1-13", "overview": "James condemns showing partiality, especially favoritism toward the rich. Believers are called to love their neighbors as themselves, fulfilling the royal law.", "reflection": "Where do you show partiality? How do you treat the poor versus the rich? What does loving your neighbor as yourself look like?", "prayer": "Confess any partiality and ask God to help you love all people equally."},
            {"day": 5, "passage": "{{translation}}: James 2:14-26", "overview": "James argues that faith without works is dead. Genuine faith produces actions—Abraham and Rahab exemplify faith that was completed by works.", "reflection": "How does your faith show itself in actions? What works demonstrate your faith? Where is your faith inactive?", "prayer": "Pray that your faith would be alive and active, producing good works."},
            {"day": 6, "passage": "{{translation}}: James 3:1-12", "overview": "James warns about the power of the tongue—though small, it can set great forests ablaze. The tongue reveals the heart and should bless God, not curse people made in His image.", "reflection": "How do you use your tongue? What damage has your speech caused? How can you better control your words?", "prayer": "Ask God to tame your tongue and help you speak only blessing and truth."},
            {"day": 7, "passage": "{{translation}}: James 3:13-18", "overview": "James contrasts earthly wisdom (characterized by jealousy and selfish ambition) with heavenly wisdom (pure, peaceable, gentle, open to reason, full of mercy and good fruits).", "reflection": "What kind of wisdom guides your life? Where do you see earthly versus heavenly wisdom? How can you pursue wisdom from above?", "prayer": "Pray for heavenly wisdom that is pure, peaceable, and full of mercy."},
            {"day": 8, "passage": "{{translation}}: James 4:1-10", "overview": "James addresses quarrels arising from unfulfilled desires, friendship with the world as enmity with God, and the call to submit to God, resist the devil, and humble ourselves.", "reflection": "What desires cause conflict in your life? Where are you friends with the world? How do you humble yourself before God?", "prayer": "Submit yourself to God, resist the devil, and ask God to lift you up in His time."},
            {"day": 9, "passage": "{{translation}}: James 4:11-17", "overview": "James warns against judging others, reminds believers of life's brevity and uncertainty, and defines sin as knowing what is right but failing to do it.", "reflection": "Who are you judging? How do you account for life's uncertainty in your plans? What good are you failing to do?", "prayer": "Ask forgiveness for judging others and pray for obedience to do the good you know."},
            {"day": 10, "passage": "{{translation}}: James 5:1-20", "overview": "James warns the rich, encourages patience in suffering, prohibits swearing, promotes prayer and confession, and urges believers to restore wandering brothers and sisters.", "reflection": "How patient are you in suffering? How is your prayer life? Who needs you to help them return to truth?", "prayer": "Pray for patience, commit to fervent prayer, and ask God to use you to restore others."}
        ]
    },

    "christ_our_high_priest.json": {
        "title": "Christ Our High Priest",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Hebrews 4:14-16", "overview": "The author presents Jesus as our great High Priest who has passed through the heavens, who sympathizes with our weaknesses, enabling us to approach God's throne with confidence.", "reflection": "What does it mean that Jesus is your High Priest? How does His sympathy with weakness encourage you? When do you need to approach God's throne with confidence?", "prayer": "Thank Jesus for being your High Priest and approach God's throne boldly for mercy and grace."},
            {"day": 2, "passage": "{{translation}}: Hebrews 5:1-10", "overview": "High priests are appointed to represent people before God, offering gifts and sacrifices. Jesus was appointed by God and learned obedience through suffering, becoming the source of eternal salvation.", "reflection": "How did Jesus fulfill the role of High Priest? What does it mean that He learned obedience through suffering? How is He the source of your salvation?", "prayer": "Thank God for appointing Jesus as your High Priest and providing eternal salvation."},
            {"day": 3, "passage": "{{translation}}: Hebrews 7:23-28", "overview": "Unlike Levitical priests who died and were replaced, Jesus holds His priesthood permanently because He lives forever. He always lives to make intercession for those who draw near to God through Him.", "reflection": "How does Jesus' permanent priesthood give you confidence? What does Christ's intercession for you mean? How do you draw near to God through Jesus?", "prayer": "Thank Jesus for His permanent priesthood and His constant intercession on your behalf."},
            {"day": 4, "passage": "{{translation}}: Hebrews 8:1-6", "overview": "Jesus serves as High Priest in the true tabernacle in heaven, not the earthly shadow. He is the mediator of a better covenant established on better promises.", "reflection": "How is the new covenant better? What does Jesus mediate for you? How does His heavenly ministry affect your daily life?", "prayer": "Praise Jesus for mediating the new covenant and serving as your High Priest in heaven."},
            {"day": 5, "passage": "{{translation}}: Hebrews 9:11-14", "overview": "Christ entered once for all into the holy places by His own blood, securing eternal redemption. His blood purifies our conscience from dead works to serve the living God.", "reflection": "How is Christ's sacrifice superior to animal sacrifices? What does purifying your conscience mean? How do you serve the living God?", "prayer": "Thank Jesus for His once-for-all sacrifice and the cleansing of your conscience."},
            {"day": 6, "passage": "{{translation}}: Hebrews 9:24-28", "overview": "Christ appeared once to put away sin by the sacrifice of Himself. Now He appears in God's presence on our behalf and will appear a second time to save those eagerly waiting for Him.", "reflection": "How does Christ represent you in God's presence? What does eagerly waiting for His return look like? How does this hope affect your life?", "prayer": "Thank Jesus for appearing in God's presence for you and express your eager hope for His return."},
            {"day": 7, "passage": "{{translation}}: Hebrews 10:19-25", "overview": "Because of Jesus' blood, believers have confidence to enter the holy places by a new and living way. We can draw near with a true heart in full assurance of faith.", "reflection": "How does Jesus' blood give you access to God? What does drawing near with a true heart mean? How can you encourage others to draw near?", "prayer": "Draw near to God with confidence, thanking Jesus for opening the way to the Father."}
        ]
    },

    "christian_identity.json": {
        "title": "Christian Identity",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: 2 Corinthians 5:17", "overview": "Paul declares that if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come. Christian identity is rooted in being made new in Christ.", "reflection": "What does being a new creation mean? What 'old things' have passed away? What 'new things' has God done in you?", "prayer": "Thank God for making you a new creation and ask Him to continue His transforming work."},
            {"day": 2, "passage": "{{translation}}: 1 Peter 2:9-10", "overview": "Peter describes believers as a chosen race, a royal priesthood, a holy nation, God's own possession, called to proclaim His excellencies. Once not a people, now you are God's people.", "reflection": "How does your identity as chosen, royal, and holy affect your life? How do you proclaim God's excellencies? What does being God's possession mean?", "prayer": "Thank God for making you His chosen possession and help you proclaim His greatness."},
            {"day": 3, "passage": "{{translation}}: Ephesians 2:19-22", "overview": "Paul reveals that believers are no longer strangers but fellow citizens with the saints and members of God's household, built on the foundation of apostles and prophets with Christ as cornerstone.", "reflection": "What does being a citizen of God's kingdom mean? How do you experience being part of God's household? How is Christ your cornerstone?", "prayer": "Thank God for making you a citizen of His kingdom and part of His family."},
            {"day": 4, "passage": "{{translation}}: Galatians 3:26-29", "overview": "All who believe are sons of God through faith in Christ Jesus. In Christ there is no Jew or Greek, slave or free, male or female—all are one and Abraham's offspring, heirs according to promise.", "reflection": "What does being a child of God mean to you? How does unity in Christ transcend human divisions? How are you an heir to God's promises?", "prayer": "Thank God for adopting you as His child and making you an heir of His promises."},
            {"day": 5, "passage": "{{translation}}: Romans 8:14-17", "overview": "Those led by the Spirit are children of God. Believers have received the Spirit of adoption, enabling them to cry 'Abba! Father!' As children, they are heirs—heirs of God and fellow heirs with Christ.", "reflection": "How does the Spirit lead you? What does calling God 'Abba' mean? How does being God's heir shape your perspective?", "prayer": "Thank God for the Spirit of adoption and for making you His child and heir."},
            {"day": 6, "passage": "{{translation}}: Colossians 3:1-4", "overview": "Paul instructs believers who have been raised with Christ to seek things above where Christ is. Their life is hidden with Christ in God, and when Christ appears, they will appear with Him in glory.", "reflection": "What does it mean that your life is hidden with Christ? How do you seek things above? How does the promise of future glory affect you now?", "prayer": "Ask God to help you seek heavenly things and live in light of your identity in Christ."},
            {"day": 7, "passage": "{{translation}}: John 1:12-13", "overview": "John declares that to all who received Jesus and believed in His name, He gave the right to become children of God—born not of blood, will of flesh, or will of man, but of God.", "reflection": "What does it mean to receive Jesus? How were you born of God? What does being God's child mean for your identity?", "prayer": "Thank God for giving you the right to be His child through faith in Jesus."}
        ]
    },

    "covenant_faithfulness.json": {
        "title": "Covenant Faithfulness",
        "default_translation": "ESV",
        "days": [
            {"day": 1, "passage": "{{translation}}: Genesis 12:1-3", "overview": "God makes a covenant with Abraham, promising to make him a great nation, bless him, and through him bless all families of the earth. God initiates covenant relationships.", "reflection": "What does God's covenant with Abraham reveal about His character? How has God's promise to bless all nations been fulfilled? How are you blessed through Abraham?", "prayer": "Thank God for His covenant faithfulness shown from the beginning with Abraham."},
            {"day": 2, "passage": "{{translation}}: Genesis 17:7-8", "overview": "God establishes an everlasting covenant with Abraham and his offspring, promising to be their God and give them the land of Canaan as an everlasting possession.", "reflection": "What does an everlasting covenant mean? How has God kept His promises to Abraham's descendants? What does it mean that God is your God?", "prayer": "Praise God for keeping His covenant promises throughout generations."},
            {"day": 3, "passage": "{{translation}}: Exodus 19:5-6", "overview": "God reminds Israel that if they obey His voice and keep His covenant, they will be His treasured possession, a kingdom of priests, and a holy nation.", "reflection": "What does being God's treasured possession mean? How does covenant relationship involve obedience? What responsibilities come with being part of God's covenant people?", "prayer": "Thank God for making you His treasured possession and help you walk in obedience."},
            {"day": 4, "passage": "{{translation}}: Jeremiah 31:31-34", "overview": "God promises a new covenant different from the old—He will put His law within them, write it on their hearts, be their God, and they will be His people. He will forgive their iniquity.", "reflection": "How is the new covenant different from the old? What does God's law written on your heart mean? How have you experienced forgiveness under the new covenant?", "prayer": "Thank God for the new covenant and for writing His law on your heart."},
            {"day": 5, "passage": "{{translation}}: Luke 22:19-20", "overview": "At the Last Supper, Jesus institutes the new covenant in His blood, shed for the forgiveness of sins. The new covenant is established through Christ's sacrifice.", "reflection": "How does Jesus' blood establish the new covenant? What does remembering His sacrifice mean? How do you experience new covenant blessings?", "prayer": "Thank Jesus for establishing the new covenant through His shed blood."},
            {"day": 6, "passage": "{{translation}}: Hebrews 8:6-13", "overview": "Christ is the mediator of a better covenant enacted on better promises. The new covenant surpasses the old, fulfilling what the old could not accomplish.", "reflection": "What makes the new covenant better? How does Jesus mediate this covenant? What promises does the new covenant include?", "prayer": "Praise Jesus for mediating a better covenant with better promises."},
            {"day": 7, "passage": "{{translation}}: 2 Corinthians 1:20", "overview": "Paul declares that all of God's promises find their 'Yes' in Christ. Through Him believers say 'Amen' to the glory of God. Jesus is the fulfillment of every covenant promise.", "reflection": "How are God's promises fulfilled in Jesus? What promises are you trusting? How do you respond 'Amen' to God's promises?", "prayer": "Thank God that all His promises are 'Yes' in Christ Jesus."}
        ]
    }
}

# Create files
comp_dir = r"c:\Users\Demetrius\Documents\sword-drill\public\bible_study_plans\comprehensive"
for filename, content in comprehensive_plans.items():
    filepath = os.path.join(comp_dir, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(content, f, indent=2, ensure_ascii=False)
    print(f"Created {filename}")

print(f"\nCompleted {len(comprehensive_plans)} comprehensive Bible study plans")
